# Generated by Django 5.2.6 on 2026-07-22 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='construction',
            fields=[
                ('type', models.CharField()),
                ('completed', models.BooleanField()),
                ('title', models.CharField(primary_key=True, serialize=False)),
                ('details', models.CharField()),
                ('location', models.CharField()),
                ('year', models.DateField(auto_now_add=True)),
                ('company', models.CharField()),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('number', models.IntegerField(blank=True)),
                ('subject', models.CharField(blank=True)),
                ('state', models.CharField(blank=True)),
                ('projecttype', models.CharField(blank=True)),
                ('budget', models.IntegerField(blank=True)),
                ('duration', models.CharField(blank=True)),
                ('discription', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyfeature1', models.CharField(blank=True)),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='APIAPP.construction')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='APIAPP.construction')),
            ],
        ),
    ]
